### ISSUE TITLE
High CPU usage when using LSP, even when idle

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/sway-vscode-plugin#57]
At least on Windows, using this VS Code plugin keeps CPU constantly at around 15% usage on my machine. The usage never reduces to near-zero, even when left idle for hours. This is rather undesirable for power-usage reasons and also impacts other workloads on the machine. I'm not actually sure if the issue is on this repo, or [FuelLabs/sway](https://github.com/FuelLabs/sway/) LSP code but this seems like the correct place to track this VS Code specific issue.

A screenshot of task manager, with `forc.exe` under VS code process:

![`forc.exe` under VS code](https://user-images.githubusercontent.com/2204863/173327585-4fbbda4f-33a9-4d91-80bd-0da55221f257.png)

### Details

Tested at commit 85104aa and on the released version of the plugin (v0.2.2).

rustc: 1.60.0 stable
VS Code: 1.67.2
OS: Windows 10 Home, version 10.0.19044
CPU: Intel i7-7700k

**Comment by JoshuaBatty** [comment]
I can't recreate this. Since this issue has been opened we no longer support windows unless through windows subsystem for linux. There has also been a number of large refactors that have occurred over the past 15 months. 

I have been measuring CPU usage on my mac over an extended period of time. The `forc-lsp` binary consistently sits at 0% CPU usage when idle as expected. We get temporary spikes to 100% CPU usage when `didChange` events are sent from the client. Looking at the image below we can see the majority of this is happening when performing type checking in the compiler. We will most likely need to implement incremental compilation (see[ this issue](https://github.com/FuelLabs/sway/issues/3381)) before we can resolve this. 

The other smaller cpu spikes you can see are when LSP requests are performed such as go to def and hover etc.. 

![Screenshot 2023-09-06 at 11 39 52 am](https://github.com/FuelLabs/sway-vscode-plugin/assets/1289413/25019652-89f0-486e-875e-ba565ae5225f)

I think we can close this issue. Feel free to reopen if you notice any high cpu usage with the current version.
