### ISSUE TITLE
Reloading window leaks forc LSP process

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/sway-vscode-plugin#58]
When editor window is reloaded, e.g. when enabling new plugins, leaves old LSP processes running. In normal use this rarely causes issues, but when developing the plugin itself it's rather problematic. Especially when combined with #57, it makes developing this plugin quite annoying.

## Reprocing

Open a sway file in the editor. Issue with command palette (ctrl-shift-p on Windows): `Developer: Reload window`.  This causes a new `forc.exe` LSP process to be spawned, as the editor reloads. However, the old process isn't cleaned up and keeps running in the background. This can be seen in task manager. Every new reload leaves one more `forc.exe` process behind.

## Details

Tested at commit 85104aa and on the released version of the plugin (v0.2.2).

rustc: 1.60.0 stable
VS Code: 1.67.2
OS: Windows 10 Home, version 10.0.19044
CPU: Intel i7-7700k

**Comment by JoshuaBatty** [comment]
Just tried to re-create this locally and was unable to do so. There seems to have been an update to `tower-lsp` since this issue was opened that rectified a similar issue happening. [https://github.com/ebkalderon/tower-lsp/issues/239](https://github.com/ebkalderon/tower-lsp/issues/239)

I'm going to close this for now and we can re-open if we notice it's still an issue for other people. 

I've also opened up [this issue](https://github.com/FuelLabs/sway/issues/4731), in order to remind the language server to handle `exit` notifications once we switch over to using a custom event loop rather than `tower-lsp`.

**Comment by JoshuaBatty** [comment]
@Braqzen just reported on Slack that he has multiple server processes running on his machine. 

![1](https://github.com/FuelLabs/sway-vscode-plugin/assets/1289413/3101ea70-ba28-4f3e-82f8-70ea5543d193)

Looks like further work needs to be done to ensure we don't have dead processes hanging around.

**Comment by sdankel** [comment]
We're still seeing this happen where orphaned forc-lsp processes will build up over time, but it doesn't repro just by reloading the window. @JoshuaBatty suggested:

Perhaps we could implement something like a heartbeat message between the server and client, once every 30 seconds or so. If the server sends a heartbeat to the client and doesn't get a response in 10 seconds then we gracefully shut down the server.

**Comment by JoshuaBatty** [comment]
The heartbeat was added in sway recently https://github.com/FuelLabs/sway/pull/5690

This issue should be resolved now.
